### ISSUE TITLE
Package version

### ISSUE THREAD

**Issue by texaco** [emacsorphanage/yafolding#1]
Hi!

It seems that newer versions of cask does not work because it is complaning about missing yafolding.el's package version.

In order to test the package I have made up a version and it worked!

The `cask` that installs by today is 

```bash
$cask --version
0.8.9pre
```

What version do you think `yafolding.el` might be?

**Comment by tarsius** [comment]
> What version do you think yafolding.el might be?

See the release *tags*.

`cask` uses `package-build.el` (which I maintain). The latter makes use of the tags, but if I remember correctly `cask` nowadays uses an old vendored copy of `package-build.el`, so that might be the issue.

I don't intend to add a `Version` header, as I don't even do that for most of my own packages. I strongly believe tags are the way and version headers suck.
